## Append samples you want in your CSV to this file as resources ##
resources:
- broker_v2alpha1_activemqartemis.yaml
- broker_v2alpha2_activemqartemis.yaml
- broker_v2alpha3_activemqartemis.yaml
- broker_v2alpha4_activemqartemis.yaml
- broker_v2alpha5_activemqartemis.yaml
- broker_v2alpha1_activemqartemisaddress.yaml
- broker_v2alpha2_activemqartemisaddress.yaml
- broker_v2alpha3_activemqartemisaddress.yaml
- broker_v2alpha1_activemqartemisscaledown.yaml
- broker_v1alpha1_activemqartemissecurity.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
