/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	brokerv1alpha1 "github.com/artemiscloud/activemq-artemis-operator/pkg/apis/broker/v1alpha1"
	versioned "github.com/artemiscloud/activemq-artemis-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/artemiscloud/activemq-artemis-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/artemiscloud/activemq-artemis-operator/pkg/client/listers/broker/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// ActiveMQArtemisAuthenticationInformer provides access to a shared informer and lister for
// ActiveMQArtemisAuthentications.
type ActiveMQArtemisAuthenticationInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.ActiveMQArtemisAuthenticationLister
}

type activeMQArtemisAuthenticationInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewActiveMQArtemisAuthenticationInformer constructs a new informer for ActiveMQArtemisAuthentication type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewActiveMQArtemisAuthenticationInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredActiveMQArtemisAuthenticationInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredActiveMQArtemisAuthenticationInformer constructs a new informer for ActiveMQArtemisAuthentication type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredActiveMQArtemisAuthenticationInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.BrokerV1alpha1().ActiveMQArtemisAuthentications(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.BrokerV1alpha1().ActiveMQArtemisAuthentications(namespace).Watch(options)
			},
		},
		&brokerv1alpha1.ActiveMQArtemisAuthentication{},
		resyncPeriod,
		indexers,
	)
}

func (f *activeMQArtemisAuthenticationInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredActiveMQArtemisAuthenticationInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *activeMQArtemisAuthenticationInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&brokerv1alpha1.ActiveMQArtemisAuthentication{}, f.defaultInformer)
}

func (f *activeMQArtemisAuthenticationInformer) Lister() v1alpha1.ActiveMQArtemisAuthenticationLister {
	return v1alpha1.NewActiveMQArtemisAuthenticationLister(f.Informer().GetIndexer())
}
