// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v3alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AcceptorType) DeepCopyInto(out *AcceptorType) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AcceptorType.
func (in *AcceptorType) DeepCopy() *AcceptorType {
	if in == nil {
		return nil
	}
	out := new(AcceptorType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccesType) DeepCopyInto(out *AccesType) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccesType.
func (in *AccesType) DeepCopy() *AccesType {
	if in == nil {
		return nil
	}
	out := new(AccesType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AccessType) DeepCopyInto(out *AccessType) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AccessType.
func (in *AccessType) DeepCopy() *AccessType {
	if in == nil {
		return nil
	}
	out := new(AccessType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActiveMQArtemis) DeepCopyInto(out *ActiveMQArtemis) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActiveMQArtemis.
func (in *ActiveMQArtemis) DeepCopy() *ActiveMQArtemis {
	if in == nil {
		return nil
	}
	out := new(ActiveMQArtemis)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ActiveMQArtemis) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActiveMQArtemisList) DeepCopyInto(out *ActiveMQArtemisList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ActiveMQArtemis, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActiveMQArtemisList.
func (in *ActiveMQArtemisList) DeepCopy() *ActiveMQArtemisList {
	if in == nil {
		return nil
	}
	out := new(ActiveMQArtemisList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ActiveMQArtemisList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActiveMQArtemisSpec) DeepCopyInto(out *ActiveMQArtemisSpec) {
	*out = *in
	in.DeploymentPlan.DeepCopyInto(&out.DeploymentPlan)
	if in.Acceptors != nil {
		in, out := &in.Acceptors, &out.Acceptors
		*out = make([]AcceptorType, len(*in))
		copy(*out, *in)
	}
	if in.Connectors != nil {
		in, out := &in.Connectors, &out.Connectors
		*out = make([]ConnectorType, len(*in))
		copy(*out, *in)
	}
	out.Console = in.Console
	out.Upgrades = in.Upgrades
	if in.RemotingIncomingInterceptors != nil {
		in, out := &in.RemotingIncomingInterceptors, &out.RemotingIncomingInterceptors
		*out = make([]RemotingIncomingInterceptorType, len(*in))
		copy(*out, *in)
	}
	if in.RemotingOutgoingInterceptors != nil {
		in, out := &in.RemotingOutgoingInterceptors, &out.RemotingOutgoingInterceptors
		*out = make([]RemotingOutgoingInterceptorType, len(*in))
		copy(*out, *in)
	}
	in.BroadcastGroups.DeepCopyInto(&out.BroadcastGroups)
	in.DiscoveryGroups.DeepCopyInto(&out.DiscoveryGroups)
	in.Diverts.DeepCopyInto(&out.Diverts)
	in.Queues.DeepCopyInto(&out.Queues)
	in.Bridges.DeepCopyInto(&out.Bridges)
	in.Federations.DeepCopyInto(&out.Federations)
	in.HaPolicy.DeepCopyInto(&out.HaPolicy)
	in.ClusterConnections.DeepCopyInto(&out.ClusterConnections)
	out.GroupingHandler = in.GroupingHandler
	out.Store = in.Store
	in.SecuritySettings.DeepCopyInto(&out.SecuritySettings)
	in.BrokerPlugins.DeepCopyInto(&out.BrokerPlugins)
	in.MetricsPluginDeprecated.DeepCopyInto(&out.MetricsPluginDeprecated)
	in.Metrics.DeepCopyInto(&out.Metrics)
	in.AddressSettings.DeepCopyInto(&out.AddressSettings)
	in.ResourceLimitSettings.DeepCopyInto(&out.ResourceLimitSettings)
	in.ConnectorServices.DeepCopyInto(&out.ConnectorServices)
	in.Addresses.DeepCopyInto(&out.Addresses)
	out.WildcardAddresses = in.WildcardAddresses
	in.Jms.DeepCopyInto(&out.Jms)
	in.LoggingProperties.DeepCopyInto(&out.LoggingProperties)
	in.ManagementContext.DeepCopyInto(&out.ManagementContext)
	in.LoginConfig.DeepCopyInto(&out.LoginConfig)
	in.JolokiaAccess.DeepCopyInto(&out.JolokiaAccess)
	in.Bootstrap.DeepCopyInto(&out.Bootstrap)
	in.ArtemisProfile.DeepCopyInto(&out.ArtemisProfile)
	if in.ArtemisRoles != nil {
		in, out := &in.ArtemisRoles, &out.ArtemisRoles
		*out = make([]ArtemisRoleType, len(*in))
		copy(*out, *in)
	}
	if in.ArtemisUsers != nil {
		in, out := &in.ArtemisUsers, &out.ArtemisUsers
		*out = make([]ArtemisUserType, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActiveMQArtemisSpec.
func (in *ActiveMQArtemisSpec) DeepCopy() *ActiveMQArtemisSpec {
	if in == nil {
		return nil
	}
	out := new(ActiveMQArtemisSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActiveMQArtemisStatus) DeepCopyInto(out *ActiveMQArtemisStatus) {
	*out = *in
	in.PodStatus.DeepCopyInto(&out.PodStatus)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActiveMQArtemisStatus.
func (in *ActiveMQArtemisStatus) DeepCopy() *ActiveMQArtemisStatus {
	if in == nil {
		return nil
	}
	out := new(ActiveMQArtemisStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActiveMQArtemisUpgrades) DeepCopyInto(out *ActiveMQArtemisUpgrades) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActiveMQArtemisUpgrades.
func (in *ActiveMQArtemisUpgrades) DeepCopy() *ActiveMQArtemisUpgrades {
	if in == nil {
		return nil
	}
	out := new(ActiveMQArtemisUpgrades)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AddresType) DeepCopyInto(out *AddresType) {
	*out = *in
	in.Anycast.DeepCopyInto(&out.Anycast)
	in.Multicast.DeepCopyInto(&out.Multicast)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AddresType.
func (in *AddresType) DeepCopy() *AddresType {
	if in == nil {
		return nil
	}
	out := new(AddresType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AddressPolicyType) DeepCopyInto(out *AddressPolicyType) {
	*out = *in
	if in.Include != nil {
		in, out := &in.Include, &out.Include
		*out = make([]IncludeType, len(*in))
		copy(*out, *in)
	}
	if in.Exclude != nil {
		in, out := &in.Exclude, &out.Exclude
		*out = make([]ExcludeType, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AddressPolicyType.
func (in *AddressPolicyType) DeepCopy() *AddressPolicyType {
	if in == nil {
		return nil
	}
	out := new(AddressPolicyType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AddressSettingType) DeepCopyInto(out *AddressSettingType) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AddressSettingType.
func (in *AddressSettingType) DeepCopy() *AddressSettingType {
	if in == nil {
		return nil
	}
	out := new(AddressSettingType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AddressSettingsType) DeepCopyInto(out *AddressSettingsType) {
	*out = *in
	if in.AddressSetting != nil {
		in, out := &in.AddressSetting, &out.AddressSetting
		*out = make([]AddressSettingType, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AddressSettingsType.
func (in *AddressSettingsType) DeepCopy() *AddressSettingsType {
	if in == nil {
		return nil
	}
	out := new(AddressSettingsType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AddressesType) DeepCopyInto(out *AddressesType) {
	*out = *in
	if in.Address != nil {
		in, out := &in.Address, &out.Address
		*out = make([]AddresType, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AddressesType.
func (in *AddressesType) DeepCopy() *AddressesType {
	if in == nil {
		return nil
	}
	out := new(AddressesType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AnycastType) DeepCopyInto(out *AnycastType) {
	*out = *in
	if in.Queue != nil {
		in, out := &in.Queue, &out.Queue
		*out = make([]QueueType, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AnycastType.
func (in *AnycastType) DeepCopy() *AnycastType {
	if in == nil {
		return nil
	}
	out := new(AnycastType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppType) DeepCopyInto(out *AppType) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppType.
func (in *AppType) DeepCopy() *AppType {
	if in == nil {
		return nil
	}
	out := new(AppType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtemisProfileType) DeepCopyInto(out *ArtemisProfileType) {
	*out = *in
	if in.JavaArgs != nil {
		in, out := &in.JavaArgs, &out.JavaArgs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.JavaArgsRun != nil {
		in, out := &in.JavaArgsRun, &out.JavaArgsRun
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtemisProfileType.
func (in *ArtemisProfileType) DeepCopy() *ArtemisProfileType {
	if in == nil {
		return nil
	}
	out := new(ArtemisProfileType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtemisRoleType) DeepCopyInto(out *ArtemisRoleType) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtemisRoleType.
func (in *ArtemisRoleType) DeepCopy() *ArtemisRoleType {
	if in == nil {
		return nil
	}
	out := new(ArtemisRoleType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArtemisUserType) DeepCopyInto(out *ArtemisUserType) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArtemisUserType.
func (in *ArtemisUserType) DeepCopy() *ArtemisUserType {
	if in == nil {
		return nil
	}
	out := new(ArtemisUserType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AuthorisationType) DeepCopyInto(out *AuthorisationType) {
	*out = *in
	in.Whitelist.DeepCopyInto(&out.Whitelist)
	in.DefaultAccess.DeepCopyInto(&out.DefaultAccess)
	in.RoleAccess.DeepCopyInto(&out.RoleAccess)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AuthorisationType.
func (in *AuthorisationType) DeepCopy() *AuthorisationType {
	if in == nil {
		return nil
	}
	out := new(AuthorisationType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BootstrapType) DeepCopyInto(out *BootstrapType) {
	*out = *in
	out.JaasSecurity = in.JaasSecurity
	in.Web.DeepCopyInto(&out.Web)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BootstrapType.
func (in *BootstrapType) DeepCopy() *BootstrapType {
	if in == nil {
		return nil
	}
	out := new(BootstrapType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BridgeType) DeepCopyInto(out *BridgeType) {
	*out = *in
	out.Filter = in.Filter
	in.Transformer.DeepCopyInto(&out.Transformer)
	in.StaticConnectors.DeepCopyInto(&out.StaticConnectors)
	out.DiscoveryGroupRef = in.DiscoveryGroupRef
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BridgeType.
func (in *BridgeType) DeepCopy() *BridgeType {
	if in == nil {
		return nil
	}
	out := new(BridgeType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BridgesType) DeepCopyInto(out *BridgesType) {
	*out = *in
	if in.Bridge != nil {
		in, out := &in.Bridge, &out.Bridge
		*out = make([]BridgeType, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BridgesType.
func (in *BridgesType) DeepCopy() *BridgesType {
	if in == nil {
		return nil
	}
	out := new(BridgesType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BroadcastGroupType) DeepCopyInto(out *BroadcastGroupType) {
	*out = *in
	if in.ConnectorRef != nil {
		in, out := &in.ConnectorRef, &out.ConnectorRef
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BroadcastGroupType.
func (in *BroadcastGroupType) DeepCopy() *BroadcastGroupType {
	if in == nil {
		return nil
	}
	out := new(BroadcastGroupType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BroadcastGroupsType) DeepCopyInto(out *BroadcastGroupsType) {
	*out = *in
	if in.BroadcastGroup != nil {
		in, out := &in.BroadcastGroup, &out.BroadcastGroup
		*out = make([]BroadcastGroupType, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BroadcastGroupsType.
func (in *BroadcastGroupsType) DeepCopy() *BroadcastGroupsType {
	if in == nil {
		return nil
	}
	out := new(BroadcastGroupsType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BrokerPluginType) DeepCopyInto(out *BrokerPluginType) {
	*out = *in
	if in.Property != nil {
		in, out := &in.Property, &out.Property
		*out = make([]PropertyType, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BrokerPluginType.
func (in *BrokerPluginType) DeepCopy() *BrokerPluginType {
	if in == nil {
		return nil
	}
	out := new(BrokerPluginType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BrokerPluginsType) DeepCopyInto(out *BrokerPluginsType) {
	*out = *in
	if in.BrokerPlugin != nil {
		in, out := &in.BrokerPlugin, &out.BrokerPlugin
		*out = make([]BrokerPluginType, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BrokerPluginsType.
func (in *BrokerPluginsType) DeepCopy() *BrokerPluginsType {
	if in == nil {
		return nil
	}
	out := new(BrokerPluginsType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CCStaticConnectorsType) DeepCopyInto(out *CCStaticConnectorsType) {
	*out = *in
	if in.ConnectorRef != nil {
		in, out := &in.ConnectorRef, &out.ConnectorRef
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CCStaticConnectorsType.
func (in *CCStaticConnectorsType) DeepCopy() *CCStaticConnectorsType {
	if in == nil {
		return nil
	}
	out := new(CCStaticConnectorsType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterConnectionType) DeepCopyInto(out *ClusterConnectionType) {
	*out = *in
	in.StaticConnectors.DeepCopyInto(&out.StaticConnectors)
	out.DiscoveryGroupRef = in.DiscoveryGroupRef
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterConnectionType.
func (in *ClusterConnectionType) DeepCopy() *ClusterConnectionType {
	if in == nil {
		return nil
	}
	out := new(ClusterConnectionType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterConnectionUriType) DeepCopyInto(out *ClusterConnectionUriType) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterConnectionUriType.
func (in *ClusterConnectionUriType) DeepCopy() *ClusterConnectionUriType {
	if in == nil {
		return nil
	}
	out := new(ClusterConnectionUriType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClusterConnectionsType) DeepCopyInto(out *ClusterConnectionsType) {
	*out = *in
	if in.ClusterConnectionUri != nil {
		in, out := &in.ClusterConnectionUri, &out.ClusterConnectionUri
		*out = make([]ClusterConnectionUriType, len(*in))
		copy(*out, *in)
	}
	if in.ClusterConnection != nil {
		in, out := &in.ClusterConnection, &out.ClusterConnection
		*out = make([]ClusterConnectionType, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClusterConnectionsType.
func (in *ClusterConnectionsType) DeepCopy() *ClusterConnectionsType {
	if in == nil {
		return nil
	}
	out := new(ClusterConnectionsType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComplexExcludeType) DeepCopyInto(out *ComplexExcludeType) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComplexExcludeType.
func (in *ComplexExcludeType) DeepCopy() *ComplexExcludeType {
	if in == nil {
		return nil
	}
	out := new(ComplexExcludeType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ComplexIncludeType) DeepCopyInto(out *ComplexIncludeType) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ComplexIncludeType.
func (in *ComplexIncludeType) DeepCopy() *ComplexIncludeType {
	if in == nil {
		return nil
	}
	out := new(ComplexIncludeType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectorServiceType) DeepCopyInto(out *ConnectorServiceType) {
	*out = *in
	if in.Param != nil {
		in, out := &in.Param, &out.Param
		*out = make([]ParamType, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectorServiceType.
func (in *ConnectorServiceType) DeepCopy() *ConnectorServiceType {
	if in == nil {
		return nil
	}
	out := new(ConnectorServiceType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectorServicesType) DeepCopyInto(out *ConnectorServicesType) {
	*out = *in
	if in.ConnectorService != nil {
		in, out := &in.ConnectorService, &out.ConnectorService
		*out = make([]ConnectorServiceType, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectorServicesType.
func (in *ConnectorServicesType) DeepCopy() *ConnectorServicesType {
	if in == nil {
		return nil
	}
	out := new(ConnectorServicesType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectorType) DeepCopyInto(out *ConnectorType) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectorType.
func (in *ConnectorType) DeepCopy() *ConnectorType {
	if in == nil {
		return nil
	}
	out := new(ConnectorType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConnectorsType) DeepCopyInto(out *ConnectorsType) {
	*out = *in
	if in.ConnectorRef != nil {
		in, out := &in.ConnectorRef, &out.ConnectorRef
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConnectorsType.
func (in *ConnectorsType) DeepCopy() *ConnectorsType {
	if in == nil {
		return nil
	}
	out := new(ConnectorsType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConsoleType) DeepCopyInto(out *ConsoleType) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConsoleType.
func (in *ConsoleType) DeepCopy() *ConsoleType {
	if in == nil {
		return nil
	}
	out := new(ConsoleType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CoreQueueType) DeepCopyInto(out *CoreQueueType) {
	*out = *in
	out.Filter = in.Filter
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CoreQueueType.
func (in *CoreQueueType) DeepCopy() *CoreQueueType {
	if in == nil {
		return nil
	}
	out := new(CoreQueueType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DatabaseStoreType) DeepCopyInto(out *DatabaseStoreType) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DatabaseStoreType.
func (in *DatabaseStoreType) DeepCopy() *DatabaseStoreType {
	if in == nil {
		return nil
	}
	out := new(DatabaseStoreType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DefaultAccessType) DeepCopyInto(out *DefaultAccessType) {
	*out = *in
	if in.Access != nil {
		in, out := &in.Access, &out.Access
		*out = make([]AccesType, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DefaultAccessType.
func (in *DefaultAccessType) DeepCopy() *DefaultAccessType {
	if in == nil {
		return nil
	}
	out := new(DefaultAccessType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DeploymentPlanType) DeepCopyInto(out *DeploymentPlanType) {
	*out = *in
	if in.MessageMigration != nil {
		in, out := &in.MessageMigration, &out.MessageMigration
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DeploymentPlanType.
func (in *DeploymentPlanType) DeepCopy() *DeploymentPlanType {
	if in == nil {
		return nil
	}
	out := new(DeploymentPlanType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoveryGroupRefType) DeepCopyInto(out *DiscoveryGroupRefType) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoveryGroupRefType.
func (in *DiscoveryGroupRefType) DeepCopy() *DiscoveryGroupRefType {
	if in == nil {
		return nil
	}
	out := new(DiscoveryGroupRefType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoveryGroupType) DeepCopyInto(out *DiscoveryGroupType) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoveryGroupType.
func (in *DiscoveryGroupType) DeepCopy() *DiscoveryGroupType {
	if in == nil {
		return nil
	}
	out := new(DiscoveryGroupType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DiscoveryGroupsType) DeepCopyInto(out *DiscoveryGroupsType) {
	*out = *in
	if in.DiscoveryGroup != nil {
		in, out := &in.DiscoveryGroup, &out.DiscoveryGroup
		*out = make([]DiscoveryGroupType, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DiscoveryGroupsType.
func (in *DiscoveryGroupsType) DeepCopy() *DiscoveryGroupsType {
	if in == nil {
		return nil
	}
	out := new(DiscoveryGroupsType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DivertType) DeepCopyInto(out *DivertType) {
	*out = *in
	in.Transformer.DeepCopyInto(&out.Transformer)
	out.Filter = in.Filter
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DivertType.
func (in *DivertType) DeepCopy() *DivertType {
	if in == nil {
		return nil
	}
	out := new(DivertType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DivertsType) DeepCopyInto(out *DivertsType) {
	*out = *in
	if in.Divert != nil {
		in, out := &in.Divert, &out.Divert
		*out = make([]DivertType, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DivertsType.
func (in *DivertsType) DeepCopy() *DivertsType {
	if in == nil {
		return nil
	}
	out := new(DivertsType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DownstreamType) DeepCopyInto(out *DownstreamType) {
	*out = *in
	in.StaticConnectors.DeepCopyInto(&out.StaticConnectors)
	out.DiscoveryGroupRef = in.DiscoveryGroupRef
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = make([]PolicyType, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DownstreamType.
func (in *DownstreamType) DeepCopy() *DownstreamType {
	if in == nil {
		return nil
	}
	out := new(DownstreamType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EntryType) DeepCopyInto(out *EntryType) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EntryType.
func (in *EntryType) DeepCopy() *EntryType {
	if in == nil {
		return nil
	}
	out := new(EntryType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExcludeType) DeepCopyInto(out *ExcludeType) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExcludeType.
func (in *ExcludeType) DeepCopy() *ExcludeType {
	if in == nil {
		return nil
	}
	out := new(ExcludeType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExcludesType) DeepCopyInto(out *ExcludesType) {
	*out = *in
	if in.ConnectorRef != nil {
		in, out := &in.ConnectorRef, &out.ConnectorRef
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExcludesType.
func (in *ExcludesType) DeepCopy() *ExcludesType {
	if in == nil {
		return nil
	}
	out := new(ExcludesType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FederationTransformerType) DeepCopyInto(out *FederationTransformerType) {
	*out = *in
	if in.Property != nil {
		in, out := &in.Property, &out.Property
		*out = make([]PropertyType, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FederationTransformerType.
func (in *FederationTransformerType) DeepCopy() *FederationTransformerType {
	if in == nil {
		return nil
	}
	out := new(FederationTransformerType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FederationType) DeepCopyInto(out *FederationType) {
	*out = *in
	if in.Upstream != nil {
		in, out := &in.Upstream, &out.Upstream
		*out = make([]UpstreamType, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Downstream != nil {
		in, out := &in.Downstream, &out.Downstream
		*out = make([]DownstreamType, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.PolicySet != nil {
		in, out := &in.PolicySet, &out.PolicySet
		*out = make([]PolicySetType, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.QueuePolicy != nil {
		in, out := &in.QueuePolicy, &out.QueuePolicy
		*out = make([]QueuePolicyType, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.AddressPolicy != nil {
		in, out := &in.AddressPolicy, &out.AddressPolicy
		*out = make([]AddressPolicyType, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Transformer != nil {
		in, out := &in.Transformer, &out.Transformer
		*out = make([]FederationTransformerType, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FederationType.
func (in *FederationType) DeepCopy() *FederationType {
	if in == nil {
		return nil
	}
	out := new(FederationType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FederationsType) DeepCopyInto(out *FederationsType) {
	*out = *in
	if in.Federation != nil {
		in, out := &in.Federation, &out.Federation
		*out = make([]FederationType, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FederationsType.
func (in *FederationsType) DeepCopy() *FederationsType {
	if in == nil {
		return nil
	}
	out := new(FederationsType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FilterType) DeepCopyInto(out *FilterType) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FilterType.
func (in *FilterType) DeepCopy() *FilterType {
	if in == nil {
		return nil
	}
	out := new(FilterType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FormatterType) DeepCopyInto(out *FormatterType) {
	*out = *in
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make([]PropertyType, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FormatterType.
func (in *FormatterType) DeepCopy() *FormatterType {
	if in == nil {
		return nil
	}
	out := new(FormatterType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GroupingHandlerType) DeepCopyInto(out *GroupingHandlerType) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GroupingHandlerType.
func (in *GroupingHandlerType) DeepCopy() *GroupingHandlerType {
	if in == nil {
		return nil
	}
	out := new(GroupingHandlerType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HaPolicyType) DeepCopyInto(out *HaPolicyType) {
	*out = *in
	in.LiveOnly.DeepCopyInto(&out.LiveOnly)
	in.Replication.DeepCopyInto(&out.Replication)
	in.SharedStore.DeepCopyInto(&out.SharedStore)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HaPolicyType.
func (in *HaPolicyType) DeepCopy() *HaPolicyType {
	if in == nil {
		return nil
	}
	out := new(HaPolicyType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HandlerType) DeepCopyInto(out *HandlerType) {
	*out = *in
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make([]PropertyType, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HandlerType.
func (in *HandlerType) DeepCopy() *HandlerType {
	if in == nil {
		return nil
	}
	out := new(HandlerType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *IncludeType) DeepCopyInto(out *IncludeType) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new IncludeType.
func (in *IncludeType) DeepCopy() *IncludeType {
	if in == nil {
		return nil
	}
	out := new(IncludeType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JaasSecurityType) DeepCopyInto(out *JaasSecurityType) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JaasSecurityType.
func (in *JaasSecurityType) DeepCopy() *JaasSecurityType {
	if in == nil {
		return nil
	}
	out := new(JaasSecurityType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JmsQueueType) DeepCopyInto(out *JmsQueueType) {
	*out = *in
	out.Selector = in.Selector
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JmsQueueType.
func (in *JmsQueueType) DeepCopy() *JmsQueueType {
	if in == nil {
		return nil
	}
	out := new(JmsQueueType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JmsTopicType) DeepCopyInto(out *JmsTopicType) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JmsTopicType.
func (in *JmsTopicType) DeepCopy() *JmsTopicType {
	if in == nil {
		return nil
	}
	out := new(JmsTopicType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JmsType) DeepCopyInto(out *JmsType) {
	*out = *in
	if in.Queue != nil {
		in, out := &in.Queue, &out.Queue
		*out = make([]JmsQueueType, len(*in))
		copy(*out, *in)
	}
	if in.Topic != nil {
		in, out := &in.Topic, &out.Topic
		*out = make([]JmsTopicType, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JmsType.
func (in *JmsType) DeepCopy() *JmsType {
	if in == nil {
		return nil
	}
	out := new(JmsType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JmxConnectorType) DeepCopyInto(out *JmxConnectorType) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JmxConnectorType.
func (in *JmxConnectorType) DeepCopy() *JmxConnectorType {
	if in == nil {
		return nil
	}
	out := new(JmxConnectorType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JolokiaAccessType) DeepCopyInto(out *JolokiaAccessType) {
	*out = *in
	if in.AllowOrigins != nil {
		in, out := &in.AllowOrigins, &out.AllowOrigins
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JolokiaAccessType.
func (in *JolokiaAccessType) DeepCopy() *JolokiaAccessType {
	if in == nil {
		return nil
	}
	out := new(JolokiaAccessType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LiveOnlyType) DeepCopyInto(out *LiveOnlyType) {
	*out = *in
	in.ScaleDown.DeepCopyInto(&out.ScaleDown)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LiveOnlyType.
func (in *LiveOnlyType) DeepCopy() *LiveOnlyType {
	if in == nil {
		return nil
	}
	out := new(LiveOnlyType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoggingPropertiesType) DeepCopyInto(out *LoggingPropertiesType) {
	*out = *in
	if in.Loggers != nil {
		in, out := &in.Loggers, &out.Loggers
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.LoggerProperties != nil {
		in, out := &in.LoggerProperties, &out.LoggerProperties
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Handlers != nil {
		in, out := &in.Handlers, &out.Handlers
		*out = make([]HandlerType, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Formatters != nil {
		in, out := &in.Formatters, &out.Formatters
		*out = make([]FormatterType, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoggingPropertiesType.
func (in *LoggingPropertiesType) DeepCopy() *LoggingPropertiesType {
	if in == nil {
		return nil
	}
	out := new(LoggingPropertiesType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoginConfigType) DeepCopyInto(out *LoginConfigType) {
	*out = *in
	if in.Entries != nil {
		in, out := &in.Entries, &out.Entries
		*out = make([]LoginEntryType, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoginConfigType.
func (in *LoginConfigType) DeepCopy() *LoginConfigType {
	if in == nil {
		return nil
	}
	out := new(LoginConfigType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoginEntryType) DeepCopyInto(out *LoginEntryType) {
	*out = *in
	if in.ModuleConfig != nil {
		in, out := &in.ModuleConfig, &out.ModuleConfig
		*out = make([]ModuleConfigType, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoginEntryType.
func (in *LoginEntryType) DeepCopy() *LoginEntryType {
	if in == nil {
		return nil
	}
	out := new(LoginEntryType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ManagementContextType) DeepCopyInto(out *ManagementContextType) {
	*out = *in
	out.Connector = in.Connector
	in.Authorisation.DeepCopyInto(&out.Authorisation)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ManagementContextType.
func (in *ManagementContextType) DeepCopy() *ManagementContextType {
	if in == nil {
		return nil
	}
	out := new(ManagementContextType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MatchType) DeepCopyInto(out *MatchType) {
	*out = *in
	out.Access = in.Access
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MatchType.
func (in *MatchType) DeepCopy() *MatchType {
	if in == nil {
		return nil
	}
	out := new(MatchType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsPluginDeprecatedType) DeepCopyInto(out *MetricsPluginDeprecatedType) {
	*out = *in
	if in.Property != nil {
		in, out := &in.Property, &out.Property
		*out = make([]PropertyType, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsPluginDeprecatedType.
func (in *MetricsPluginDeprecatedType) DeepCopy() *MetricsPluginDeprecatedType {
	if in == nil {
		return nil
	}
	out := new(MetricsPluginDeprecatedType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricsType) DeepCopyInto(out *MetricsType) {
	*out = *in
	in.Plugin.DeepCopyInto(&out.Plugin)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricsType.
func (in *MetricsType) DeepCopy() *MetricsType {
	if in == nil {
		return nil
	}
	out := new(MetricsType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ModuleConfigType) DeepCopyInto(out *ModuleConfigType) {
	*out = *in
	if in.Properties != nil {
		in, out := &in.Properties, &out.Properties
		*out = make([]PropertyType, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ModuleConfigType.
func (in *ModuleConfigType) DeepCopy() *ModuleConfigType {
	if in == nil {
		return nil
	}
	out := new(ModuleConfigType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MulticastType) DeepCopyInto(out *MulticastType) {
	*out = *in
	if in.Queue != nil {
		in, out := &in.Queue, &out.Queue
		*out = make([]QueueType, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MulticastType.
func (in *MulticastType) DeepCopy() *MulticastType {
	if in == nil {
		return nil
	}
	out := new(MulticastType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ParamType) DeepCopyInto(out *ParamType) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ParamType.
func (in *ParamType) DeepCopy() *ParamType {
	if in == nil {
		return nil
	}
	out := new(ParamType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PermissionType) DeepCopyInto(out *PermissionType) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PermissionType.
func (in *PermissionType) DeepCopy() *PermissionType {
	if in == nil {
		return nil
	}
	out := new(PermissionType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PluginType) DeepCopyInto(out *PluginType) {
	*out = *in
	if in.Property != nil {
		in, out := &in.Property, &out.Property
		*out = make([]PropertyType, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PluginType.
func (in *PluginType) DeepCopy() *PluginType {
	if in == nil {
		return nil
	}
	out := new(PluginType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicySetType) DeepCopyInto(out *PolicySetType) {
	*out = *in
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = make([]PolicyType, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicySetType.
func (in *PolicySetType) DeepCopy() *PolicySetType {
	if in == nil {
		return nil
	}
	out := new(PolicySetType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PolicyType) DeepCopyInto(out *PolicyType) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PolicyType.
func (in *PolicyType) DeepCopy() *PolicyType {
	if in == nil {
		return nil
	}
	out := new(PolicyType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PropertyType) DeepCopyInto(out *PropertyType) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PropertyType.
func (in *PropertyType) DeepCopy() *PropertyType {
	if in == nil {
		return nil
	}
	out := new(PropertyType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueuePolicyType) DeepCopyInto(out *QueuePolicyType) {
	*out = *in
	if in.Include != nil {
		in, out := &in.Include, &out.Include
		*out = make([]ComplexIncludeType, len(*in))
		copy(*out, *in)
	}
	if in.Exclude != nil {
		in, out := &in.Exclude, &out.Exclude
		*out = make([]ComplexExcludeType, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueuePolicyType.
func (in *QueuePolicyType) DeepCopy() *QueuePolicyType {
	if in == nil {
		return nil
	}
	out := new(QueuePolicyType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueueType) DeepCopyInto(out *QueueType) {
	*out = *in
	out.Filter = in.Filter
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueueType.
func (in *QueueType) DeepCopy() *QueueType {
	if in == nil {
		return nil
	}
	out := new(QueueType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *QueuesType) DeepCopyInto(out *QueuesType) {
	*out = *in
	if in.Queue != nil {
		in, out := &in.Queue, &out.Queue
		*out = make([]CoreQueueType, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new QueuesType.
func (in *QueuesType) DeepCopy() *QueuesType {
	if in == nil {
		return nil
	}
	out := new(QueuesType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemotingIncomingInterceptorType) DeepCopyInto(out *RemotingIncomingInterceptorType) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemotingIncomingInterceptorType.
func (in *RemotingIncomingInterceptorType) DeepCopy() *RemotingIncomingInterceptorType {
	if in == nil {
		return nil
	}
	out := new(RemotingIncomingInterceptorType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RemotingOutgoingInterceptorType) DeepCopyInto(out *RemotingOutgoingInterceptorType) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RemotingOutgoingInterceptorType.
func (in *RemotingOutgoingInterceptorType) DeepCopy() *RemotingOutgoingInterceptorType {
	if in == nil {
		return nil
	}
	out := new(RemotingOutgoingInterceptorType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicationColocatedType) DeepCopyInto(out *ReplicationColocatedType) {
	*out = *in
	in.Excludes.DeepCopyInto(&out.Excludes)
	out.Master = in.Master
	in.Slave.DeepCopyInto(&out.Slave)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicationColocatedType.
func (in *ReplicationColocatedType) DeepCopy() *ReplicationColocatedType {
	if in == nil {
		return nil
	}
	out := new(ReplicationColocatedType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicationMasterType) DeepCopyInto(out *ReplicationMasterType) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicationMasterType.
func (in *ReplicationMasterType) DeepCopy() *ReplicationMasterType {
	if in == nil {
		return nil
	}
	out := new(ReplicationMasterType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicationSlaveType) DeepCopyInto(out *ReplicationSlaveType) {
	*out = *in
	in.ScaleDown.DeepCopyInto(&out.ScaleDown)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicationSlaveType.
func (in *ReplicationSlaveType) DeepCopy() *ReplicationSlaveType {
	if in == nil {
		return nil
	}
	out := new(ReplicationSlaveType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ReplicationType) DeepCopyInto(out *ReplicationType) {
	*out = *in
	out.Master = in.Master
	in.Slave.DeepCopyInto(&out.Slave)
	in.Colocated.DeepCopyInto(&out.Colocated)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ReplicationType.
func (in *ReplicationType) DeepCopy() *ReplicationType {
	if in == nil {
		return nil
	}
	out := new(ReplicationType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceLimitSettingType) DeepCopyInto(out *ResourceLimitSettingType) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceLimitSettingType.
func (in *ResourceLimitSettingType) DeepCopy() *ResourceLimitSettingType {
	if in == nil {
		return nil
	}
	out := new(ResourceLimitSettingType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ResourceLimitSettingsType) DeepCopyInto(out *ResourceLimitSettingsType) {
	*out = *in
	if in.ResourceLimitSetting != nil {
		in, out := &in.ResourceLimitSetting, &out.ResourceLimitSetting
		*out = make([]ResourceLimitSettingType, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ResourceLimitSettingsType.
func (in *ResourceLimitSettingsType) DeepCopy() *ResourceLimitSettingsType {
	if in == nil {
		return nil
	}
	out := new(ResourceLimitSettingsType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleAccessType) DeepCopyInto(out *RoleAccessType) {
	*out = *in
	if in.Match != nil {
		in, out := &in.Match, &out.Match
		*out = make([]MatchType, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleAccessType.
func (in *RoleAccessType) DeepCopy() *RoleAccessType {
	if in == nil {
		return nil
	}
	out := new(RoleAccessType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RoleMappingType) DeepCopyInto(out *RoleMappingType) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RoleMappingType.
func (in *RoleMappingType) DeepCopy() *RoleMappingType {
	if in == nil {
		return nil
	}
	out := new(RoleMappingType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ScaleDownType) DeepCopyInto(out *ScaleDownType) {
	*out = *in
	out.DiscoveryGroupRef = in.DiscoveryGroupRef
	in.Connectors.DeepCopyInto(&out.Connectors)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ScaleDownType.
func (in *ScaleDownType) DeepCopy() *ScaleDownType {
	if in == nil {
		return nil
	}
	out := new(ScaleDownType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecuritySettingPluginType) DeepCopyInto(out *SecuritySettingPluginType) {
	*out = *in
	if in.Setting != nil {
		in, out := &in.Setting, &out.Setting
		*out = make([]SettingType, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecuritySettingPluginType.
func (in *SecuritySettingPluginType) DeepCopy() *SecuritySettingPluginType {
	if in == nil {
		return nil
	}
	out := new(SecuritySettingPluginType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecuritySettingType) DeepCopyInto(out *SecuritySettingType) {
	*out = *in
	if in.Permission != nil {
		in, out := &in.Permission, &out.Permission
		*out = make([]PermissionType, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecuritySettingType.
func (in *SecuritySettingType) DeepCopy() *SecuritySettingType {
	if in == nil {
		return nil
	}
	out := new(SecuritySettingType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SecuritySettingsType) DeepCopyInto(out *SecuritySettingsType) {
	*out = *in
	if in.SecuritySetting != nil {
		in, out := &in.SecuritySetting, &out.SecuritySetting
		*out = make([]SecuritySettingType, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	in.SecuritySettingPlugin.DeepCopyInto(&out.SecuritySettingPlugin)
	if in.RoleMapping != nil {
		in, out := &in.RoleMapping, &out.RoleMapping
		*out = make([]RoleMappingType, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SecuritySettingsType.
func (in *SecuritySettingsType) DeepCopy() *SecuritySettingsType {
	if in == nil {
		return nil
	}
	out := new(SecuritySettingsType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SelectorType) DeepCopyInto(out *SelectorType) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SelectorType.
func (in *SelectorType) DeepCopy() *SelectorType {
	if in == nil {
		return nil
	}
	out := new(SelectorType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SettingType) DeepCopyInto(out *SettingType) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SettingType.
func (in *SettingType) DeepCopy() *SettingType {
	if in == nil {
		return nil
	}
	out := new(SettingType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharedStoreColocatedType) DeepCopyInto(out *SharedStoreColocatedType) {
	*out = *in
	out.Master = in.Master
	in.Slave.DeepCopyInto(&out.Slave)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharedStoreColocatedType.
func (in *SharedStoreColocatedType) DeepCopy() *SharedStoreColocatedType {
	if in == nil {
		return nil
	}
	out := new(SharedStoreColocatedType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharedStoreMasterType) DeepCopyInto(out *SharedStoreMasterType) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharedStoreMasterType.
func (in *SharedStoreMasterType) DeepCopy() *SharedStoreMasterType {
	if in == nil {
		return nil
	}
	out := new(SharedStoreMasterType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharedStoreSlaveType) DeepCopyInto(out *SharedStoreSlaveType) {
	*out = *in
	in.ScaleDown.DeepCopyInto(&out.ScaleDown)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharedStoreSlaveType.
func (in *SharedStoreSlaveType) DeepCopy() *SharedStoreSlaveType {
	if in == nil {
		return nil
	}
	out := new(SharedStoreSlaveType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SharedStoreType) DeepCopyInto(out *SharedStoreType) {
	*out = *in
	out.Master = in.Master
	in.Slave.DeepCopyInto(&out.Slave)
	in.Colocated.DeepCopyInto(&out.Colocated)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SharedStoreType.
func (in *SharedStoreType) DeepCopy() *SharedStoreType {
	if in == nil {
		return nil
	}
	out := new(SharedStoreType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StaticConnectorsType) DeepCopyInto(out *StaticConnectorsType) {
	*out = *in
	if in.ConnectorRef != nil {
		in, out := &in.ConnectorRef, &out.ConnectorRef
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StaticConnectorsType.
func (in *StaticConnectorsType) DeepCopy() *StaticConnectorsType {
	if in == nil {
		return nil
	}
	out := new(StaticConnectorsType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StoreType) DeepCopyInto(out *StoreType) {
	*out = *in
	out.DatabaseStore = in.DatabaseStore
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StoreType.
func (in *StoreType) DeepCopy() *StoreType {
	if in == nil {
		return nil
	}
	out := new(StoreType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TransformerType) DeepCopyInto(out *TransformerType) {
	*out = *in
	if in.Property != nil {
		in, out := &in.Property, &out.Property
		*out = make([]PropertyType, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TransformerType.
func (in *TransformerType) DeepCopy() *TransformerType {
	if in == nil {
		return nil
	}
	out := new(TransformerType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UpstreamType) DeepCopyInto(out *UpstreamType) {
	*out = *in
	in.StaticConnectors.DeepCopyInto(&out.StaticConnectors)
	out.DiscoveryGroupRef = in.DiscoveryGroupRef
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = make([]PolicyType, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UpstreamType.
func (in *UpstreamType) DeepCopy() *UpstreamType {
	if in == nil {
		return nil
	}
	out := new(UpstreamType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WebType) DeepCopyInto(out *WebType) {
	*out = *in
	if in.Apps != nil {
		in, out := &in.Apps, &out.Apps
		*out = make([]AppType, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WebType.
func (in *WebType) DeepCopy() *WebType {
	if in == nil {
		return nil
	}
	out := new(WebType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WhitelistType) DeepCopyInto(out *WhitelistType) {
	*out = *in
	if in.Entry != nil {
		in, out := &in.Entry, &out.Entry
		*out = make([]EntryType, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WhitelistType.
func (in *WhitelistType) DeepCopy() *WhitelistType {
	if in == nil {
		return nil
	}
	out := new(WhitelistType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WildcardAddressesType) DeepCopyInto(out *WildcardAddressesType) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WildcardAddressesType.
func (in *WildcardAddressesType) DeepCopy() *WildcardAddressesType {
	if in == nil {
		return nil
	}
	out := new(WildcardAddressesType)
	in.DeepCopyInto(out)
	return out
}
