apiVersion: broker.amq.io/v3alpha1
kind: ActiveMQArtemis
metadata:
  name: ex-aao
spec:
  deploymentPlan:
    size: 1
    image: quay.io/artemiscloud/activemq-artemis-operator:latest
    journalType: aio
