apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
  name: activemq-artemis-controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
      - args:
        - --zap-log-level=debug
        - --zap-encoder=console
        - --leader-elect
        command:
        - /home/activemq-artemis-operator/bin/entrypoint
        env:
        - name: OPERATOR_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['name']
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: WATCH_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_2150
          value: quay.io/artemiscloud/activemq-artemis-broker-init:0.2.2
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_2160
          value: quay.io/artemiscloud/activemq-artemis-broker-init:0.2.4
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_2180
          value: quay.io/artemiscloud/activemq-artemis-broker-init:0.2.10
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_2200
          value: quay.io/artemiscloud/activemq-artemis-broker-init:0.2.12
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_100
          value: quay.io/artemiscloud/activemq-artemis-broker-init:0.2.12
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_101
          value: quay.io/artemiscloud/activemq-artemis-broker-init:1.0.1
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_102
          value: quay.io/artemiscloud/activemq-artemis-broker-init:1.0.2
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Init_103
          value: quay.io/artemiscloud/activemq-artemis-broker-init:1.0.5
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_2150
          value: quay.io/artemiscloud/activemq-artemis-broker-kubernetes:0.2.0
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_2160
          value: quay.io/artemiscloud/activemq-artemis-broker-kubernetes:0.2.1
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_2180
          value: quay.io/artemiscloud/activemq-artemis-broker-kubernetes:0.2.7
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_2200
          value: quay.io/artemiscloud/activemq-artemis-broker-kubernetes:0.2.9
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_100
          value: quay.io/artemiscloud/activemq-artemis-broker-kubernetes:0.2.9
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_101
          value: quay.io/artemiscloud/activemq-artemis-broker-kubernetes:1.0.1
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_102
          value: quay.io/artemiscloud/activemq-artemis-broker-kubernetes:1.0.2
        - name: RELATED_IMAGE_ActiveMQ_Artemis_Broker_Kubernetes_103
          value: quay.io/artemiscloud/activemq-artemis-broker-kubernetes:1.0.5
        - name: ENABLE_WEBHOOKS
          value: "false"
        image: quay.io/hgao/operator:6642
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        name: manager
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        securityContext:
          allowPrivilegeEscalation: false
      securityContext:
        runAsNonRoot: true
      serviceAccountName: activemq-artemis-controller-manager
      terminationGracePeriodSeconds: 10
