apiVersion: v1
kind: Service
metadata:
  name: activemq-artemis-webhook-service
  namespace: activemq-artemis-operator
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  selector:
    control-plane: controller-manager
