# permissions for end users to view activemqartemis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: activemqartemis-viewer-role
rules:
- apiGroups:
  - broker.amq.io
  resources:
  - activemqartemis
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - broker.amq.io
  resources:
  - activemqartemis/status
  verbs:
  - get
