# permissions for end users to edit activemqartemis.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: activemqartemis-editor-role
rules:
- apiGroups:
  - broker.amq.io
  resources:
  - activemqartemis
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - broker.amq.io
  resources:
  - activemqartemis/status
  verbs:
  - get
