name: 'Pull Request Check'
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize

jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          # ref: ${{github.event.after}}
          # this only get last: MSG=$(git log --format=%B -n 1 ${{github.event.after}}) &&
          # ref: ${{github.event.pull_request.commits}}
      - name: Get Commit Message
        run: |
          CMTN=${{github.event.pull_request.commits}}
          nlines=-1
          for (( N=1; N<=$CMTN; N++ ))
          do
            prev_lines=$(($nlines+1))
            nlines=0
            while IFS= read -r line
            do
              nlines=$((nlines+1))
              if (( $nlines == $prev_lines+1 )); then
                if ! [[ "$line" =~ ^\[#([0-9])+\]\ .+$|^(\[NO-JIRA\]\ ).+$ ]]; then
                  echo "Commit message should begin with [#nnn] or [NO-JIRA]"
                  echo "but it is: $line"
                  exit 1
                fi
              fi
            done <<< $(git log --format=%B -n $N ${{github.event.after}})
          done
      - name: Show github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
