name: 'Pull Request Check'
on:
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  pull_request_target:
    types:
      - opened
      - edited
      - reopened
      - synchronize
  push:
    branches:
      - main

jobs:
  check-commit-message:
    name: Check Commit Message
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v2
        with:
          # fetch-depth: 0
          # ref: ${{github.event.after}}
          # this only get last: MSG=$(git log --format=%B -n 1 ${{github.event.after}}) &&
          ref: ${{github.event.pull_request.commits}}
      - name: Get Commit Message
        run: >
          echo "checking message: ${{github.event.pull_request.commits}}"
