// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActiveMQArtemisAuthentication) DeepCopyInto(out *ActiveMQArtemisAuthentication) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActiveMQArtemisAuthentication.
func (in *ActiveMQArtemisAuthentication) DeepCopy() *ActiveMQArtemisAuthentication {
	if in == nil {
		return nil
	}
	out := new(ActiveMQArtemisAuthentication)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ActiveMQArtemisAuthentication) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActiveMQArtemisAuthenticationList) DeepCopyInto(out *ActiveMQArtemisAuthenticationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ActiveMQArtemisAuthentication, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActiveMQArtemisAuthenticationList.
func (in *ActiveMQArtemisAuthenticationList) DeepCopy() *ActiveMQArtemisAuthenticationList {
	if in == nil {
		return nil
	}
	out := new(ActiveMQArtemisAuthenticationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ActiveMQArtemisAuthenticationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActiveMQArtemisAuthenticationSpec) DeepCopyInto(out *ActiveMQArtemisAuthenticationSpec) {
	*out = *in
	in.Domain.DeepCopyInto(&out.Domain)
	in.CertDomain.DeepCopyInto(&out.CertDomain)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActiveMQArtemisAuthenticationSpec.
func (in *ActiveMQArtemisAuthenticationSpec) DeepCopy() *ActiveMQArtemisAuthenticationSpec {
	if in == nil {
		return nil
	}
	out := new(ActiveMQArtemisAuthenticationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActiveMQArtemisAuthenticationStatus) DeepCopyInto(out *ActiveMQArtemisAuthenticationStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActiveMQArtemisAuthenticationStatus.
func (in *ActiveMQArtemisAuthenticationStatus) DeepCopy() *ActiveMQArtemisAuthenticationStatus {
	if in == nil {
		return nil
	}
	out := new(ActiveMQArtemisAuthenticationStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertDomainType) DeepCopyInto(out *CertDomainType) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Debug != nil {
		in, out := &in.Debug, &out.Debug
		*out = new(bool)
		**out = **in
	}
	if in.Users != nil {
		in, out := &in.Users, &out.Users
		*out = make([]CertUserType, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertDomainType.
func (in *CertDomainType) DeepCopy() *CertDomainType {
	if in == nil {
		return nil
	}
	out := new(CertDomainType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CertUserType) DeepCopyInto(out *CertUserType) {
	*out = *in
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CertUserType.
func (in *CertUserType) DeepCopy() *CertUserType {
	if in == nil {
		return nil
	}
	out := new(CertUserType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DomainType) DeepCopyInto(out *DomainType) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.LoginModules != nil {
		in, out := &in.LoginModules, &out.LoginModules
		*out = make([]LoginModuleType, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DomainType.
func (in *DomainType) DeepCopy() *DomainType {
	if in == nil {
		return nil
	}
	out := new(DomainType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *LoginModuleType) DeepCopyInto(out *LoginModuleType) {
	*out = *in
	if in.Options != nil {
		in, out := &in.Options, &out.Options
		*out = make([]OptionType, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new LoginModuleType.
func (in *LoginModuleType) DeepCopy() *LoginModuleType {
	if in == nil {
		return nil
	}
	out := new(LoginModuleType)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OptionType) DeepCopyInto(out *OptionType) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OptionType.
func (in *OptionType) DeepCopy() *OptionType {
	if in == nil {
		return nil
	}
	out := new(OptionType)
	in.DeepCopyInto(out)
	return out
}
